id: AFC340991
title: Verses on the Buddha's Previous Lives
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:00:46.178018
  last_modified_at: 2022-03-01 04:00:46.178025
